#pragma config(Hubs,  S1, HTMotor,  HTMotor,  none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     ,               sensorSoundDB)
#pragma config(Sensor, S3,     ,               sensorI2CCustom)
#pragma config(Sensor, S4,     ,               sensorI2CCustom)
#pragma config(Motor,  mtr_S1_C1_1,      ,             tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,      ,             tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,      ,             tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,      ,             tmotorTetrix, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*
*	Autonomous.c
*	Main autonomous program. This file handles all strategies and decision making.
*	The program will run a menu used to determine the different settings that the users want.
*	It will then make decisions based on those settings.
*	Options include defensive or offensive, starting position, wait times, etc.
*
*	THIS CODE IS PROVIDED AS-IS AND WITHOUT WARRANTY.
*	THIS CODE IS OPEN FOR DISTRIBUTION AND MODIFICATION
*
*	FTC Team #5029, The Powerstackers
*	powerstackersftc.weebly.com
*	github.com/powerstackers
*/

#include "C:\Users\Owner\Documents\Robotics\Teleop summer\headers\AutoFunctions.h"

task main()
{
	writeDebugStreamLine("********************\n*\n*\tAUTONOMOUS PROGRAM\n*\n********************");
	initializeRobot();
	nxtDisplayCenteredBigTextLine(0, "AUTO");
	nxtDisplayCenteredBigTextLine(2, "READY");
	//waitForStart();
	nxtDisplayCenteredBigTextLine(2, "RUNNING");
	//turnDegrees(20.0, 34);
	//goTicks(30, 30, true);
	findGoalOrientation();

}
