#pragma config(StandardModel, "PS CASCADE EFFECT")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*
*	AutoFunctionTest.c
*	Test program for various autonomous functions.
*	Copyright (C) 2015 Powerstackers
*
*	This program is free software: you can redistribute it and/or modify
*	it under the terms of the GNU General Public License as published by
*	the Free Software Foundation, either version 3 of the License, or
*	(at your option) any later version.
*
*	This program is distributed in the hope that it will be useful,
*	but WITHOUT ANY WARRANTY; without even the implied warranty of
*	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
*	GNU General Public License for more details.
*
*	You should have received a copy of the GNU General Public License
*	along with this program.  If not, see <http://www.gnu.org/licenses/>.
*
*	FTC Team #5029, The Powerstackers
*	powerstackersftc.com
*	github.com/powerstackers
*	January 19 2015
*	Version 0.1
*/

#include "headers/AutoFunctions.h"
#include "headers/CascadeEffect.h"
#include "headers/Menu.h"

task main()
{
	initializeRobot();
	//waitForStart();
//turnDegrees (-87,75);

	//char goalFacing = findGoalOrientation();
	//goTicks(inchesToTicks(-4),75);
	//wallAlign(ALIGN_BACKWARD);

	  //goTicks(inchesToTicks(15), 100);	// Move 3 feet forwards at full power
			// Turn towards the opponent rolling goals
			//turnDegrees(60, 75);
			// Drive forward to disrupt the opponent rolling goals
			//goTicks(inchesToTicks(49), 75);
			//goTicks(inchesToTicks(-12), 100);

			// turn slightly to get the rest of the goals
			//turnDegrees(40, 75);
			//goTicks(inchesToTicks(28), 75);
			//goTicks(inchesToTicks(-28), 100);

			// Turn and go around the center goal towards our rolling goals
			//turnDegrees(-45, 50);
			//goTicks(inchesToTicks(-36), 100);
			//turnDegrees(60, 50);
			//goTicks(inchesToTicks(-20), 100);
			// END DEFENSE
	irAlign();
}
