#pragma config(StandardModel, "PSCE NEW ROBOT")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*
*	EncoderTest.c
*	Code used to test the encoders. Used for testing purposes only.
*	Copyright (C) 2015 Powerstackers
*
*	This program is free software: you can redistribute it and/or modify
*	it under the terms of the GNU General Public License as published by
*	the Free Software Foundation, either version 3 of the License, or
*	(at your option) any later version.
*
*	This program is distributed in the hope that it will be useful,
*	but WITHOUT ANY WARRANTY; without even the implied warranty of
*	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
*	GNU General Public License for more details.
*
*	You should have received a copy of the GNU General Public License
*	along with this program.  If not, see <http://www.gnu.org/licenses/>.
*
*	FTC Team #5029, The Powerstackers
*	powerstackersftc.com
*	github.com/powerstackers
*	December 31 2014
*	Version 0.1
*/

// Include files to handle the joystick messages, and some basic functions.
#include "../drivers/JoystickDriver.c"
#include "../Tele-Op/TeleopFunctions.h"
#include "../Robot.h"

// Store the motor that is currently in use.
short motorUsing = mLift;
bool buttonTrapDoorJustPushed = false;

task main()
{
	nMotorEncoder[motorUsing] = 0;	// Set the encoder value to 0

	// Make sure that the NXT LCD screen is clear
	bDisplayDiagnostics = false;
	eraseDisplay();

	initializeRobot();

	// Loop until the FCS kills the process
	while(true)
	{
		// Retrieve the joystick values
		getJoystickSettings(joystick);
		getCustomJoystickSettings();

		if(buttonLiftEncoderReset)
		{
			nMotorEncoder[mLift] = 0;
		}

		if(abs(stickLiftTarget) > 15)
		{
			writeDebugStreamLine("UP");
			motor[mLift] = stickLiftTarget>0? 50 : -50;
		}
		else
		{
			motor[mLift] = 0;
		}

		if(buttonTrapDoor && !buttonTrapDoorJustPushed)
		{
			switchTrapdoor();
			buttonTrapDoorJustPushed = true;
		}
		if(!buttonTrapDoor)
			buttonTrapDoorJustPushed = false;

		nxtDisplayTextLine(2, "Enc: %d", nMotorEncoder[mLift]);
	}	// END MAIN LOOP
}	// END
