#pragma config(Sensor, S2,     SMUX,           sensorI2CCustom)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "headers/multiplexer.h"

task main()
{
	while(true)
	{
		getIREnhanced(irLeft, LEFT);
		nxtDisplayCenteredBigTextLine(1, "%d", irStrengthLeft);
		nxtDisplayCenteredBigTextLine(5, "%d", irDirectionLeft);
	}
}
