#pragma config(StandardModel, "PS CASCADE EFFECT")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*
*	IRtest.c
*	Functional test for the IR detector. Finds which of three positions the center goal is facing.
*
*	THIS CODE IS PROVIDED AS-IS AND WITHOUT WARRANTY.
*	THIS CODE IS OPEN FOR DISTRIBUTION AND MODIFICATION.
*
*	FTC Team #5029, The Powerstackers
*	powerstackersftc.com
*	github.com/powerstackers
*	December 31 2014
*	Version 0.1
*/

#include "headers/Sensors.h"

#define positionA 80
#define positionB 95
#define positionC 70

task main()
{
	StartTask(getSmux);
	gettingIr=true;
	wait10Msec(35);

	int avg = ((irStrengthLeft + irStrengthRight) / 2);
	int diffA = abs(avg - positionA);
	int diffB = abs(avg - positionB);
	int diffC = abs(avg - positionC);
	char facing;

	if(diffA < diffB && diffA < diffC)
		facing = 'a';
	else if(diffB < diffA && diffB < diffC)
		facing = 'b';
	else
		facing = 'c';
	writeDebugStreamLine("Left:\t\t%d", irStrengthLeft);
	writeDebugStreamLine("Right:\t\t%d", irStrengthRight);
	writeDebugStreamLine("Average:\t%d", avg);
	writeDebugStreamLine("The thing is in position %c", facing);

	StopAllTasks();
}
