#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     m1,            tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     m2,            tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     m3,            tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     m4,            tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_1,     m5,            tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_2,     m6,            tmotorTetrix, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*
*	MotorControllerTest.c
*	Program to test motor controllers. Contains three motor controllers that all get flashed
*	at various power levels, one after the other.
*
*	THIS CODE IS PROVIDED AS-IS AND WITHOUT WARRANTY.
*	THIS CODE IS OPEN FOR DISTRIBUTION AND MODIFICATION
*
*	FTC Team #5029, The Powerstackers
*	powerstackersftc.com
*	github.com/powerstackers
*	December 31 2014
*	Version 0.1
*/

task main()
{
	nxtDisplayTextLine(0, "Motor testing program");
	nxtDisplayTextLine(1, "running mtr:");

	// Run the different motors at different speeds
	short motors[6] = {m1,m2,m3,m4,m5,m6};
	for(int i = 0; i<6; i++){
		nxtDisplayTextLine(1, "running mtr: %d", motors[i]-2);
		motor[motors[i]] = 100;
		nxtDisplayTextLine(2, "Pwr: 100");
		wait10Msec(200);
		motor[motors[i]] = 50;
		nxtDisplayTextLine(2, "Pwr: 50");
		wait10Msec(200);
		motor[motors[i]] = 25;
		nxtDisplayTextLine(2, "Pwr: 25");
		wait10Msec(200);
		PlaySound(soundBeepBeep);
	}
}
