#pragma config(StandardModel, "PS CASCADE EFFECT")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "headers/Sensors.h"

task main()
{

	//StartTask(getSmux);
	while(true){
		nxtDisplayTextLine(0, "UsonFr: %d", getUltraStrength(ultraFront));
		nxtDisplayTextLine(1, "UsonBa: %d", getUltraStrength(ultraBack));
		nxtDisplayTextLine(2, "IR: %d", getIRStrength(infraRed));
	}


}
