#pragma config(Sensor, S1,     sUltra,         sensorSONAR)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "lego-ultrasound.h"

task main()
{
	while(true)
	{
		displayTextLine(2, "USSensor:%d", SensorValue[sUltra]);
		//displayTextLine(3, "Xander's Driver:%d", USreadDist(sUltra));


	}
}
