/*
*	UltrasonicTest.c
*	Program to test the ultrasonic sensors, and use them for collision avoidance.
*
*	THIS CODE IS PROVIDED AS-IS AND WITHOUT WARRANTY.
*	THIS CODE IS OPEN FOR DISTRIBUTION AND MODIFICATION
*
*	FTC Team #5029, The Powerstackers
*	powerstackersftc.weebly.com
*	github.com/powerstackers
*/

#pragma config(Hubs,  S1, HTMotor,  HTMotor,  none,     none)
#pragma config(Sensor, S2,     SMUX1,          sensorI2CCustom)
#pragma config(Motor,  motorA,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  motorB,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  motorC,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  mtr_S1_C1_1,     mDriveLeft,    tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     mDriveRight,   tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C2_1,     mBrush,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     mLift,         tmotorTetrix, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "headers/AutoFunctions.h"



task main()
{
	StartTask(autonomous);
}

task autonomous()
{
	StartTask(avoidCollision);
	StartTask(getSmux);
	while(true)
	{
		motor[mDriveLeft] = -50;
		motor[mDriveRight] = -50;
		nxtDisplayTextLine(5, "F:%d", SensorValue[sUltraFront]);
		nxtDisplayTextLine(6, "B:%d", SensorValue[sUltraBack]);
	}
}
