#pragma config(StandardModel, "PS CASCADE EFFECT")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*
*	AfterMatch.c
*	Program to run motors for reset, outside of match play.
*	Copyright (C) 2015 Powerstackers
*
*	This program is free software: you can redistribute it and/or modify
*	it under the terms of the GNU General Public License as published by
*	the Free Software Foundation, either version 3 of the License, or
*	(at your option) any later version.
*
*	This program is distributed in the hope that it will be useful,
*	but WITHOUT ANY WARRANTY; without even the implied warranty of
*	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
*	GNU General Public License for more details.
*
*	You should have received a copy of the GNU General Public License
*	along with this program.  If not, see <http://www.gnu.org/licenses/>.
*
*	FTC Team #5029, The Powerstackers
*	powerstackersftc.com
*	github.com/powerstackers
*	January 8 2015
*	Version 0.1
*/

#include "TeleopFunctions.h"

#define UP_BUTTON 	kRightButton
#define DOWN_BUTTON	kLeftButton
#define NEXT_BUTTON	kEnterButton

task main()
{
	bDisplayDiagnostics = false;
	eraseDisplay();

	int selectedLine = 0;
	int previousLine = 5;
	nxtDisplayStringAt(94, 63, "<");

	nxtDisplayBigTextLine(6, "AFTMATCH");

	bool enterRecentlyPressed = false;

	while(true)
	{
		nxtDisplayString(0, "Lift:  %d   ", motor[mLift]);
		nxtDisplayString(1, "Horiz: %d   ", motor[mHoriz]);
		nxtDisplayString(2, "Tip:   %d   ", motor[mTip]);
		nxtDisplayString(3, "Brush: %d   ", motor[mBrush]);
		nxtDisplayString(4, "Flaps: %s   ", (servo[rFlapLeft]==flapLeftClosedPosition)?"closed":"open");
		nxtDisplayString(5, "Grab:  %s   ", (servo[rGrabber]==grabberClosedPosition)?"closed":"open");

		if(nNxtButtonPressed==NEXT_BUTTON&&!enterRecentlyPressed)
		{
			enterRecentlyPressed = true;
			previousLine = selectedLine;
			selectedLine++;
			if(selectedLine>5)
				selectedLine = 0;
			PlaySound(soundBlip);
		}
		if(nNxtButtonPressed!=NEXT_BUTTON)
			enterRecentlyPressed = false;

		nxtDisplayStringAt(94, 63-(selectedLine*8), "<");
		nxtDisplayStringAt(94, 63-(previousLine*8), " ");

		if(nNxtButtonPressed==UP_BUTTON||nNxtButtonPressed==DOWN_BUTTON)
		{
			if(selectedLine==0)
				motor[mLift] = (nNxtButtonPressed==UP_BUTTON)?liftMotorSpeed:-1*liftMotorSpeed;

			if(selectedLine==1)
				motor[mHoriz] = (nNxtButtonPressed==UP_BUTTON)?horizMotorSpeed:-1*horizMotorSpeed;

			if(selectedLine==2)
				motor[mTip] = (nNxtButtonPressed==UP_BUTTON) ?tipMotorSpeed:-1*tipMotorSpeed;

			if(selectedLine==3)
				motor[mBrush] = (nNxtButtonPressed==UP_BUTTON)?brushMotorSpeed:-1*brushMotorSpeed;
		}
		else
		{
			motor[mLift] = 0;
			motor[mHoriz] = 0;
			motor[mTip] = 0;
			motor[mBrush] = 0;
		}

	}
}
