#pragma config(StandardModel, "PS CASCADE EFFECT")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*
*	AfterMatch.c
*	Program to run motors for reset, outside of match play.
*	Copyright (C) 2015 Powerstackers
*
*	This program is free software: you can redistribute it and/or modify
*	it under the terms of the GNU General Public License as published by
*	the Free Software Foundation, either version 3 of the License, or
*	(at your option) any later version.
*
*	This program is distributed in the hope that it will be useful,
*	but WITHOUT ANY WARRANTY; without even the implied warranty of
*	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
*	GNU General Public License for more details.
*
*	You should have received a copy of the GNU General Public License
*	along with this program.  If not, see <http://www.gnu.org/licenses/>.
*
*	FTC Team #5029, The Powerstackers
*	powerstackersftc.com
*	github.com/powerstackers
*	January 8 2015
*	Version 0.1
*/

// Include a file that has some basic functions
#include "TeleopFunctions.h"

// Define constants for the buttons (this way we can remap them if we need to)
#define UP_BUTTON 	kRightButton
#define DOWN_BUTTON	kLeftButton
#define NEXT_BUTTON	kEnterButton

task main()
{
	// Put all motors and servos to their normal starting positions
	initializeRobot();

	// Make sure that the NXT screen is empty
	bDisplayDiagnostics = false;
	eraseDisplay();

	int selectedLine = 0;			// Store the currently selected line
	int previousLine = 5;			// Store the previously selected line

	// Start the selection indicator off at the top line
	nxtDisplayStringAt(94, 63, "<");

	// Display the name of the program in big letters at the bottom of the screen
	nxtDisplayBigTextLine(6, "AFTMATCH");

	// Store whether the enter button has been recently pressed
	bool enterRecentlyPressed 	= false;

	while(true)
	{
		/*
		*	Print all the motor and servo names and their values to the NXT LCD screen
		*/
		nxtDisplayString(0, "Lift:  %d   ", motor[mLift]);
		nxtDisplayString(1, "Horiz: %d   ", motor[mHoriz]);
		nxtDisplayString(2, "Tip:   %d   ", motor[mTip]);
		nxtDisplayString(3, "Brush: %d   ", motor[mBrush]);
		nxtDisplayString(4, "TrapD: %s", (servo[rTrapDoor]==trapDoorClosedPosition)?"closed":"open  ");
		nxtDisplayString(5, "Grab:  %s", (servo[rGrabber]==grabberClosedPosition)?"closed":"open  ");

		/*
		*	NEXT BUTTON
		*	If the NEXT button is pressed, it has been recently pressed. Set the previous line to the current line,
		*	and the current line to the next line. If the new current line is past the bottom, bring it up to the top.
		*	Play a short sound to notify the drivers.
		*/
		if(nNxtButtonPressed==NEXT_BUTTON&&!enterRecentlyPressed)
		{
			enterRecentlyPressed = true;
			previousLine = selectedLine;
			selectedLine++;
			if(selectedLine>5)
				selectedLine = 0;
			PlaySound(soundBlip);
		}
		// If the NEXT button is not pressed, it has not been recently pressed.
		if(nNxtButtonPressed!=NEXT_BUTTON)
			enterRecentlyPressed = false;

		/*
		*	Erase the selection indicator from the previously selected line, and write a selection icon
		*	at the newly selected line.
		*/
		nxtDisplayStringAt(94, 63-(selectedLine*8), "<");
		nxtDisplayStringAt(94, 63-(previousLine*8), " ");

		/*
		*	UP AND DOWN BUTTONS
		*	If either the up or down button is pressed, change the value of the currently selected motor or servo.
		*/
		if(nNxtButtonPressed==UP_BUTTON||nNxtButtonPressed==DOWN_BUTTON)
		{
			/*
			*	For motors, if the UP button is pressed, run the motor forwards. If the DOWN button is pressed,
			*	run the motor in reverse.
			*/
			if(selectedLine==0)
				motor[mLift] = (nNxtButtonPressed==UP_BUTTON)?liftMotorSpeed:-1*liftMotorSpeed;

			if(selectedLine==1)
				motor[mHoriz] = (nNxtButtonPressed==UP_BUTTON)?horizMotorSpeed:-1*horizMotorSpeed;

			if(selectedLine==2)
				motor[mTip] = (nNxtButtonPressed==UP_BUTTON) ?tipMotorSpeed:-1*tipMotorSpeed;

			if(selectedLine==3)
				motor[mBrush] = (nNxtButtonPressed==UP_BUTTON)?brushMotorSpeed:-1*brushMotorSpeed;

			/*
			*	For servos, if the UP button is pressed, switch the servo to the open position. If the DOWN button
			*	is pressed, set the servo to its closed position.
			*/
			if(selectedLine==4)
				servo[rTrapDoor] = (nNxtButtonPressed==UP_BUTTON)?trapDoorOpenPosition:trapDoorClosedPosition;
			if(selectedLine==5)
				servo[rGrabber] = (nNxtButtonPressed==UP_BUTTON)?grabberOpenPosition:grabberClosedPosition;
		}

		/*
		*	If neither the UP or DOWN buttons are pressed, turn the motors off.
		*/
		else
		{
			motor[mLift] = 0;
			motor[mHoriz] = 0;
			motor[mTip] = 0;
			motor[mBrush] = 0;
		}

	}// END MAIN LOOP

}// END
