#pragma config(Hubs,  S1, HTMotor,  HTMotor,  none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     SMUX,           sensorNone)
#pragma config(Sensor, S3,     sGyro,          sensorNone)
#pragma config(Sensor, S4,     sLiftStop,      sensorNone)
#pragma config(Motor,  motorA,          mFlagRaise1,   tmotorNXT, openLoop)
#pragma config(Motor,  motorB,          mFlagRaise2,   tmotorNXT, openLoop)
#pragma config(Motor,  motorC,          mBlockStop,    tmotorNXT, openLoop)
#pragma config(Motor,  mtr_S1_C1_1,     mDriveLeft,    tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     mDriveRight,   tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C2_1,     mBrush,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     motorG,        tmotorTetrix, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

// Include a file to handle messages from the joystick
#include "JoystickDriver.c"


short stick_value_left;
short stick_value_right;



void get_custom_joystick_settings ()
{
	stick_value_right	= joystick.joy1_y2;
	stick_value_left = joystick.joy1_y1;
}





/*
*	stickToMotorValue
*	Convert the -127 - 128 stick value to a -100 - 100 motor value
*/
short stickToMotorValue(short stickValue)
{
	return (short) ( (float)stickValue * 0.78125);
}

/*
*	initializeRobot
*	Sets the robot's motors and servos to their starting values. Also
*	prepares sensors and multiplexers, as well as the NXT.
*/
void initializeRobot()
{

}

task main()
{
	// Sets robot to starting positions
	initializeRobot();

	// Wait for the start of the match
	waitForStart();

	// Clear the display
	bDisplayDiagnostics = false;
	eraseDisplay();

	// Loop forever
	while(true)
	{
		// Updates joystick settings
		getJoystickSettings(joystick);

		get_custom_joystick_settings ();

		/*
		*
		*	Print information to the NXT screen
		*
		*/
		nxtDisplayTextLine(1, "LeftDr:%d", motor[mDriveLeft]);		// Left drive motor settings
		nxtDisplayTextLine(2, "RightDr:%d", motor[mDriveRight]);	// Right drive motor settings
		nxtDisplayTextLine(3, "LeftSt:%d", stick_value_left);			// Left joystick
		nxtDisplayTextLine(4, "RightSt:%d", stick_value_right);		// Right joystick

		// If button 3 on joystick 1 is pressed
		if(joy1Btn(3) == 1)
		{
			// Move both motors together based on left joystick position
			motor[mDriveLeft] = (abs(stick_value_left) > 15)? stickToMotorValue(stick_value_left) : 0;
			motor[mDriveRight] = (abs(stick_value_left) > 15)? stickToMotorValue(stick_value_left) : 0;
		}
		// If button 3 on joystick 1 is not pressed
		else
		{
			// Move the motors independently, based on their respective joystick positions
			motor[mDriveLeft] = (abs(stick_value_left) > 15)? stickToMotorValue(stick_value_left) : 0;
			motor[mDriveRight] = (abs(stick_value_right) > 15)? stickToMotorValue(stick_value_right) : 0;
		}

		// If button 6 on joystick 1 is pressed, set the brush motor to full power.
		// If it is not pressed, set the brush motor to 0.
		motor[mBrush] = (joy1Btn(6) == 1)? -100 : 0;

	}
}
