#pragma config(StandardModel, "PS CASCADE EFFECT")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#define numMotors 8

task watchMotors ()
{
	long prevEncoderValue[numMotors];
	long encoderThreshold = 300;

	for(short i = 0; i<numMotors; i++)
	{
		prevEncoderValue[i] = nMotorEncoder[i];
	}

	while(true)
	{
		for(short i = 0; i<numMotors; i++)
		{
			if(motor[i]!=0&&abs(prevEncoderValue[i]-nMotorEncoder[i])>encoderThreshold)
			{
				short motorSpeed = motor [i];
				hogCPU();
				allMotorsTo(0);

				if(i==mDriveLeft || i==mDriveRight)
				{

				}
			}
		}




	}


}
